### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by michaelglass** [jrochkind/cap_git_tools#6]
this repo has no license. I don't understand how I can use it.

Please pick one: http://choosealicense.com/

**Comment by jrochkind** [comment]
I will add a license, it was an oversight. However, this gem works with Capistrano 2.x only; Cap 3.x has been out for a while, so this may not be useful to you at the moment.

**Comment by michaelglass** [comment]
we're already using it.  Lawyers asked for licenses for open source software we use.

**Comment by michaelglass** [comment]
thanks!
